package com.lingshan.analytics.service;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lingshan.analytics.dto.DecisionActionDto;
import com.lingshan.analytics.entity.*;
import com.lingshan.analytics.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;
@Service
public class DecisionActionService {
 private static final Map<String,Set<String>> TRANSITIONS=Map.of("PROPOSED",Set.of("ACCEPTED","DISMISSED"),"ACCEPTED",Set.of("IN_PROGRESS","DISMISSED"),"IN_PROGRESS",Set.of("COMPLETED","DISMISSED"),"COMPLETED",Set.of(),"DISMISSED",Set.of());
 private final DecisionActionRepository actions; private final DecisionCardRecordRepository cards; private final EventRepository events; private final ObjectMapper json;
 public DecisionActionService(DecisionActionRepository a,DecisionCardRecordRepository c,EventRepository e,ObjectMapper j){actions=a;cards=c;events=e;json=j;}
 @Transactional(readOnly=true) public List<DecisionActionDto> list(String snapshotId){if(snapshotId==null||snapshotId.isBlank())throw new IllegalArgumentException("决策快照不能为空");return actions.findBySnapshotIdOrderByCreatedAtDesc(snapshotId).stream().map(this::dto).toList();}
 @Transactional public DecisionActionDto create(String cardId,String text){DecisionCardRecord card=cards.findById(cardId).orElseThrow(()->new NoSuchElementException("未找到决策卡")); if(text==null||text.isBlank())throw new IllegalArgumentException("待办内容不能为空"); LocalDateTime now=LocalDateTime.now(); DecisionAction a=new DecisionAction();a.setId(UUID.randomUUID().toString());a.setCardId(cardId);a.setSnapshotId(card.getSnapshotId());a.setActionText(text.trim());a.setStatus("PROPOSED");a.setCreatedAt(now);a.setUpdatedAt(now);return dto(actions.save(a));}
 @Transactional public DecisionActionDto update(String id,String status,String owner,LocalDateTime dueAt,String note){DecisionAction a=find(id);if(status!=null&&!status.equals(a.getStatus())){if(!TRANSITIONS.getOrDefault(a.getStatus(),Set.of()).contains(status))throw new IllegalStateException("不允许的待办状态跳转");a.setStatus(status);if("ACCEPTED".equals(status))a.setAcceptedAt(LocalDateTime.now());if("COMPLETED".equals(status))a.setCompletedAt(LocalDateTime.now());}a.setOwner(trim(owner));a.setDueAt(dueAt);a.setNote(trim(note));a.setUpdatedAt(LocalDateTime.now());return dto(actions.save(a));}
 @Transactional public DecisionActionDto evaluate(String id,LocalDateTime bs,LocalDateTime be,LocalDateTime rs,LocalDateTime re){window(bs,be);window(rs,re);DecisionAction a=find(id);Map<String,Object>b=metrics(events.findByTsBetween(bs,be)),r=metrics(events.findByTsBetween(rs,re));a.setBaselineWindowStart(bs);a.setBaselineWindowEnd(be);a.setEvaluationWindowStart(rs);a.setEvaluationWindowEnd(re);a.setBaselineMetricsJson(write(b));a.setResultMetricsJson(write(r));a.setUpdatedAt(LocalDateTime.now());return dto(actions.save(a));}
 private Map<String,Object> metrics(List<AnalyticsEvent> list){long q=list.stream().filter(e->Set.of("user_message","quick_ask").contains(e.getEvent())).count(),m=count(list,"user_message"),n=list.stream().filter(e->"user_message".equals(e.getEvent())&&"negative".equals(e.getSentiment())).count();List<Double>lat=list.stream().filter(e->"ai_reply".equals(e.getEvent())&&e.getLatencyMs()!=null).map(AnalyticsEvent::getLatencyMs).sorted().toList();List<Double>ratings=list.stream().filter(e->e.getEvent()!=null&&e.getEvent().startsWith("rate_")&&e.getRatingValue()!=null).map(AnalyticsEvent::getRatingValue).toList();Map<String,Object> out=new LinkedHashMap<>();out.put("questionCount",q);out.put("negativeRatio",m==0?0.0:(double)n/m);out.put("routeExposures",count(list,"route_expose"));out.put("routeClicks",count(list,"route_click"));out.put("spotVisits",count(list,"spot_enter"));out.put("ticketAmount",amount(list,"ticket_purchase","ticket_cost"));out.put("purchaseAmount",amount(list,"purchase","amount"));out.put("averageRating",ratings.stream().mapToDouble(Double::doubleValue).average().orElse(0));out.put("p90LatencyMs",lat.isEmpty()?0:lat.get(Math.max(0,(int)Math.ceil(lat.size()*.9)-1)));return out;}
 private long count(List<AnalyticsEvent> l,String name){return l.stream().filter(e->name.equals(e.getEvent())).count();} private double amount(List<AnalyticsEvent>l,String event,String key){return l.stream().filter(e->event.equals(e.getEvent())).mapToDouble(e->number(map(e.getProperties()).get(key))).sum();}
 private DecisionAction find(String id){return actions.findById(id).orElseThrow(()->new NoSuchElementException("未找到决策待办"));} private void window(LocalDateTime s,LocalDateTime e){if(s==null||e==null||!e.isAfter(s))throw new IllegalArgumentException("评估时间窗口无效");}
 private DecisionActionDto dto(DecisionAction a){return new DecisionActionDto(a.getId(),a.getCardId(),a.getSnapshotId(),a.getActionText(),a.getStatus(),a.getOwner(),a.getDueAt(),a.getNote(),a.getAcceptedAt(),a.getCompletedAt(),a.getBaselineWindowStart(),a.getBaselineWindowEnd(),a.getEvaluationWindowStart(),a.getEvaluationWindowEnd(),map(a.getBaselineMetricsJson()),map(a.getResultMetricsJson()));}
 private Map<String,Object> map(String s){if(s==null||s.isBlank())return Map.of();try{return json.readValue(s,new TypeReference<>(){});}catch(JsonProcessingException e){return Map.of();}} private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException("无法保存评估指标",e);}} private double number(Object v){return v instanceof Number n?Math.max(0,n.doubleValue()):0;} private String trim(String v){return v==null||v.isBlank()?null:v.trim();}
}
